#!/bin/env python3
import psutil
from helper.pango import colored

def format_percentage(percentage):
	padded_percentage = f'{round(percentage): >3}'
	if percentage < 25:
		return colored(padded_percentage, 'white')
	elif percentage < 50:
		return colored(padded_percentage, 'yellow')
	elif percentage < 75:
		return colored(padded_percentage, 'orange')
	return colored(padded_percentage, 'red')

if __name__ == '__main__':
	core_count = psutil.cpu_count()
	cpu_usage = psutil.cpu_percent(interval=1, percpu=True)

	colored_unit = colored('%', 'grey')
	message = ' '.join([
		f'{format_percentage(percent)}{colored_unit}'
	 		for percent in cpu_usage
	 ])
	print(message)
